/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projektprogramu;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author szymo
 */
public class ProjektProgramu extends javax.swing.JFrame {

    /**
     * Creates new form ProjektProgramu
     */
    public ProjektProgramu() {
        initComponents();
        f = new File("Szymon_Kurzynski.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLImie = new javax.swing.JLabel();
        jLNazwisko = new javax.swing.JLabel();
        jLKlasa = new javax.swing.JLabel();
        jLPrzedmiot = new javax.swing.JLabel();
        jLOcena = new javax.swing.JLabel();
        jImie = new javax.swing.JTextField();
        jNazwisko = new javax.swing.JTextField();
        jKlasa = new javax.swing.JComboBox<>();
        jPrzedmiot = new javax.swing.JComboBox<>();
        jOcena = new javax.swing.JSlider();
        jWpisy = new javax.swing.JLabel();
        jWczytanie = new javax.swing.JButton();
        jZapisanie = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPole = new javax.swing.JTextArea();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLImie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLImie.setText("Podaj imie :");

        jLNazwisko.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNazwisko.setText("Podaj nazwisko :");

        jLKlasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLKlasa.setText("Klasa :");

        jLPrzedmiot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPrzedmiot.setText("Przedmiot :");

        jLOcena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLOcena.setText("Ocena :");

        jImie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImieActionPerformed(evt);
            }
        });

        jKlasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1Ptn", "2Ptn", "3Ptn", " ", " " }));

        jPrzedmiot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chemia", "Matematyka", "Geografia", "Angielski" }));

        jOcena.setBackground(new java.awt.Color(0, 204, 204));
        jOcena.setMajorTickSpacing(1);
        jOcena.setMaximum(6);
        jOcena.setMinorTickSpacing(1);
        jOcena.setPaintLabels(true);
        jOcena.setPaintTicks(true);
        jOcena.setSnapToTicks(true);
        jOcena.setValue(3);

        jWpisy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jWpisy.setText("Wszystkie wpisy");

        jWczytanie.setText("Wczytaj dane");
        jWczytanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWczytanieActionPerformed(evt);
            }
        });

        jZapisanie.setText("Zapisz dane");
        jZapisanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZapisanieActionPerformed(evt);
            }
        });

        jPole.setColumns(20);
        jPole.setRows(5);
        jScrollPane2.setViewportView(jPole);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLOcena)
                            .addGap(18, 18, 18)
                            .addComponent(jOcena, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLImie)
                                .addComponent(jLNazwisko)
                                .addComponent(jLKlasa)
                                .addComponent(jLPrzedmiot))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jNazwisko)
                                .addComponent(jImie)
                                .addComponent(jKlasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPrzedmiot, 0, 128, Short.MAX_VALUE))))
                    .addComponent(jZapisanie))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jWpisy)
                        .addGap(29, 29, 29)
                        .addComponent(jWczytanie, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLImie)
                    .addComponent(jImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWpisy)
                    .addComponent(jWczytanie))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNazwisko)
                    .addComponent(jNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLKlasa)
                    .addComponent(jKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrzedmiot)
                    .addComponent(jPrzedmiot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLOcena))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jZapisanie)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jImieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jImieActionPerformed

    private void jZapisanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZapisanieActionPerformed
        String imie = jImie.getText();
        String nazwisko = jNazwisko.getText();
        String klasa = jKlasa.getSelectedItem().toString();
        String przedmiot = jPrzedmiot.getSelectedItem().toString();
        String ocena = "" + jOcena.getValue();
        try {
        FileWriter fw = new FileWriter(f);
            fw.write(imie+";");
            fw.write(nazwisko+";");
            fw.write(klasa+";");
            fw.write(przedmiot+";");
            fw.write(ocena);
            jPole.setText(" ");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(ProjektProgramu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jZapisanieActionPerformed

    private void jWczytanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWczytanieActionPerformed
        try{
            Scanner sc = new Scanner(f);
            String data = " ";
            while(sc.hasNext()){
                data += sc.nextLine()+"\n";
            }
            jPole.setText(data);
            
        }   catch(FileNotFoundException ex) {
            Logger.getLogger(ProjektProgramu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jWczytanieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjektProgramu().setVisible(true);
            }
        });
    }
    private File f;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jImie;
    private javax.swing.JComboBox<String> jKlasa;
    private javax.swing.JLabel jLImie;
    private javax.swing.JLabel jLKlasa;
    private javax.swing.JLabel jLNazwisko;
    private javax.swing.JLabel jLOcena;
    private javax.swing.JLabel jLPrzedmiot;
    private javax.swing.JTextField jNazwisko;
    private javax.swing.JSlider jOcena;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jPole;
    private javax.swing.JComboBox<String> jPrzedmiot;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jWczytanie;
    private javax.swing.JLabel jWpisy;
    private javax.swing.JButton jZapisanie;
    // End of variables declaration//GEN-END:variables
}
